$(document).ready(function(){
  $("#hide").click(function(){
    $("p").hide();
  });
  $("#show").click(function(){
    $("p").show();
  });
   $("#div1").hide();
    $("button").click(function(){
    $("#div1").toggle();
  });
    });